export const COUNTRY_LIST = [
  { key: "albania", name: "Albania" },
  { key: "algeria", name: "Algeria" },
  { key: "andorra", name: "Andorra" },
  { key: "angola", name: "Angola" },
  { key: "antigua_and_barbuda", name: "Antigua and Barbuda" },
  { key: "argentina", name: "Argentina" },
  { key: "armenia", name: "Armenia" },
  { key: "australia", name: "Australia" },
  { key: "austria", name: "Austria" },
  { key: "azerbaijan", name: "Azerbaijan" },
  { key: "bahamas", name: "Bahamas" },
  { key: "bahrain", name: "Bahrain" },
  { key: "bangladesh", name: "Bangladesh" },
  { key: "barbados", name: "Barbados" },
  { key: "belarus", name: "Belarus" },
  { key: "belgium", name: "Belgium" },
  { key: "belize", name: "Belize" },
  { key: "benin", name: "Benin" },
  { key: "bhutan", name: "Bhutan" },
  { key: "bolivia", name: "Bolivia" },
  { key: "bosnia_and_herzegovina", name: "Bosnia and Herzegovina" },
  { key: "botswana", name: "Botswana" },
  { key: "brazil", name: "Brazil" },
  { key: "brunei", name: "Brunei" },
  { key: "bulgaria", name: "Bulgaria" },
  { key: "burkina_faso", name: "Burkina Faso" },
  { key: "burundi", name: "Burundi" },
  { key: "cabo_verde", name: "Cabo Verde" },
  { key: "cambodia", name: "Cambodia" },
  { key: "cameroon", name: "Cameroon" },
  { key: "canada", name: "Canada" },
  { key: "central_african_republic", name: "Central African Republic" },
  { key: "chad", name: "Chad" },
  { key: "chile", name: "Chile" },
  { key: "china", name: "China" },
  { key: "colombia", name: "Colombia" },
  { key: "comoros", name: "Comoros" },
  { key: "congo", name: "Congo" },
  { key: "costa_rica", name: "Costa Rica" },
  { key: "croatia", name: "Croatia" },
  { key: "cuba", name: "Cuba" },
  { key: "cyprus", name: "Cyprus" },
  { key: "czech_republic", name: "Czech Republic" },
  { key: "democratic_republic_of_the_congo", name: "Democratic Republic of the Congo" },
  { key: "denmark", name: "Denmark" },
  { key: "djibouti", name: "Djibouti" },
  { key: "dominica", name: "Dominica" },
  { key: "dominican_republic", name: "Dominican Republic" },
  { key: "ecuador", name: "Ecuador" },
  { key: "egypt", name: "Egypt" },
  { key: "el_salvador", name: "El Salvador" },
  { key: "equatorial_guinea", name: "Equatorial Guinea" },
  { key: "eritrea", name: "Eritrea" },
  { key: "estonia", name: "Estonia" },
  { key: "eswatini", name: "Eswatini" },
  { key: "ethiopia", name: "Ethiopia" },
  { key: "fiji", name: "Fiji" },
  { key: "finland", name: "Finland" },
  { key: "france", name: "France" },
  { key: "gabon", name: "Gabon" },
  { key: "gambia", name: "Gambia" },
  { key: "georgia", name: "Georgia" },
  { key: "germany", name: "Germany" },
  { key: "ghana", name: "Ghana" },
  { key: "greece", name: "Greece" },
  { key: "grenada", name: "Grenada" },
  { key: "guatemala", name: "Guatemala" },
  { key: "guinea", name: "Guinea" },
  { key: "guinea_bissau", name: "Guinea-Bissau" },
  { key: "guyana", name: "Guyana" },
  { key: "haiti", name: "Haiti" },
  { key: "honduras", name: "Honduras" },
  { key: "hungary", name: "Hungary" },
  { key: "iceland", name: "Iceland" },
  { key: "india", name: "India" },
  { key: "indonesia", name: "Indonesia" },
  { key: "iran", name: "Iran" },
  { key: "iraq", name: "Iraq" },
  { key: "ireland", name: "Ireland" },
  { key: "israel", name: "Israel" },
  { key: "italy", name: "Italy" },
  { key: "jamaica", name: "Jamaica" },
  { key: "japan", name: "Japan" },
  { key: "jordan", name: "Jordan" },
  { key: "kazakhstan", name: "Kazakhstan" },
  { key: "kenya", name: "Kenya" },
  { key: "kiribati", name: "Kiribati" },
  { key: "kuwait", name: "Kuwait" },
  { key: "kyrgyzstan", name: "Kyrgyzstan" },
  { key: "laos", name: "Laos" },
  { key: "latvia", name: "Latvia" },
  { key: "lebanon", name: "Lebanon" },
  { key: "lesotho", name: "Lesotho" },
  { key: "liberia", name: "Liberia" },
  { key: "libya", name: "Libya" },
  { key: "liechtenstein", name: "Liechtenstein" },
  { key: "lithuania", name: "Lithuania" },
  { key: "luxembourg", name: "Luxembourg" },
  { key: "madagascar", name: "Madagascar" },
  { key: "malawi", name: "Malawi" },
  { key: "malaysia", name: "Malaysia" },
  { key: "maldives", name: "Maldives" },
  { key: "mali", name: "Mali" },
  { key: "malta", name: "Malta" },
  { key: "marshall_islands", name: "Marshall Islands" },
  { key: "mauritania", name: "Mauritania" },
  { key: "mauritius", name: "Mauritius" },
  { key: "mexico", name: "Mexico" },
  { key: "micronesia", name: "Micronesia" },
  { key: "moldova", name: "Moldova" },
  { key: "monaco", name: "Monaco" },
  { key: "mongolia", name: "Mongolia" },
  { key: "montenegro", name: "Montenegro" },
  { key: "morocco", name: "Morocco" },
  { key: "mozambique", name: "Mozambique" },
  { key: "myanmar", name: "Myanmar" },
  { key: "namibia", name: "Namibia" },
  { key: "nauru", name: "Nauru" },
  { key: "nepal", name: "Nepal" },
  { key: "netherlands", name: "Netherlands" },
  { key: "new_zealand", name: "New Zealand" },
  { key: "nicaragua", name: "Nicaragua" },
  { key: "niger", name: "Niger" },
  { key: "nigeria", name: "Nigeria" },
  { key: "north_korea", name: "North Korea" },
  { key: "north_macedonia", name: "North Macedonia" },
  { key: "norway", name: "Norway" },
  { key: "oman", name: "Oman" },
  { key: "pakistan", name: "Pakistan" },
  { key: "palau", name: "Palau" },
  { key: "palestine", name: "Palestine" },
  { key: "panama", name: "Panama" },
  { key: "papua_new_guinea", name: "Papua New Guinea" },
  { key: "paraguay", name: "Paraguay" },
  { key: "peru", name: "Peru" },
  { key: "philippines", name: "Philippines" },
  { key: "poland", name: "Poland" },
  { key: "portugal", name: "Portugal" },
  { key: "qatar", name: "Qatar" },
  { key: "romania", name: "Romania" },
  { key: "russia", name: "Russia" },
  { key: "rwanda", name: "Rwanda" },
  { key: "saint_kitts_and_nevis", name: "Saint Kitts and Nevis" },
  { key: "saint_lucia", name: "Saint Lucia" },
  { key: "saint_vincent_and_the_grenadines", name: "Saint Vincent and the Grenadines" },
  { key: "samoa", name: "Samoa" },
  { key: "san_marino", name: "San Marino" },
  { key: "sao_tome_and_principe", name: "São Tomé and Príncipe" },
  { key: "saudi_arabia", name: "Saudi Arabia" },
  { key: "senegal", name: "Senegal" },
  { key: "serbia", name: "Serbia" },
  { key: "seychelles", name: "Seychelles" },
  { key: "sierra_leone", name: "Sierra Leone" },
  { key: "singapore", name: "Singapore" },
  { key: "slovakia", name: "Slovakia" },
  { key: "slovenia", name: "Slovenia" },
  { key: "solomon_islands", name: "Solomon Islands" },
  { key: "somalia", name: "Somalia" },
  { key: "south_africa", name: "South Africa" },
  { key: "south_korea", name: "South Korea" },
  { key: "south_sudan", name: "South Sudan" },
  { key: "spain", name: "Spain" },
  { key: "sri_lanka", name: "Sri Lanka" },
  { key: "sudan", name: "Sudan" },
  { key: "suriname", name: "Suriname" },
  { key: "sweden", name: "Sweden" },
  { key: "switzerland", name: "Switzerland" },
  { key: "syria", name: "Syria" },
  { key: "taiwan", name: "Taiwan" },
  { key: "tajikistan", name: "Tajikistan" },
  { key: "tanzania", name: "Tanzania" },
  { key: "thailand", name: "Thailand" },
  { key: "timor_leste", name: "Timor-Leste" },
  { key: "togo", name: "Togo" },
  { key: "tonga", name: "Tonga" },
  { key: "trinidad_and_tobago", name: "Trinidad and Tobago" },
  { key: "tunisia", name: "Tunisia" },
  { key: "turkey", name: "Turkey" },
  { key: "turkmenistan", name: "Turkmenistan" },
  { key: "tuvalu", name: "Tuvalu" },
  { key: "uganda", name: "Uganda" },
  { key: "ukraine", name: "Ukraine" },
  { key: "united_arab_emirates", name: "United Arab Emirates" },
  { key: "united_kingdom", name: "United Kingdom" },
  { key: "united_states", name: "United States" },
  { key: "uruguay", name: "Uruguay" },
  { key: "uzbekistan", name: "Uzbekistan" },
  { key: "vanuatu", name: "Vanuatu" },
  { key: "vatican_city", name: "Vatican City" },
  { key: "venezuela", name: "Venezuela" },
  { key: "vietnam", name: "Vietnam" },
  { key: "yemen", name: "Yemen" },
  { key: "zambia", name: "Zambia" },
  { key: "zimbabwe", name: "Zimbabwe" },
];
